export const DSSIGN_COMPONENT = {
  Anchor: { component: '@iflorens/hui-plus/packages/_es/anchor' },
  AnnexTable: { component: '@iflorens/hui-plus/packages/_es/annex' },
  Annex: { component: '@iflorens/hui-plus/packages/_es/annex' },
  AutoComplete: { component: '@iflorens/hui-plus/packages/_es/auto-complete' },
  AutoCompleteTable: { component: '@iflorens/hui-plus/packages/_es/auto-complete-table' },
  Button: { component: '@iflorens/hui-plus/packages/_es/button' },
  LongButton: { component: '@iflorens/hui-plus/packages/_es/button' },
  Card: { component: '@iflorens/hui-plus/packages/_es/card' },
  CardItem: { component: '@iflorens/hui-plus/packages/_es/card' },
  LeaseItem: { component: '@iflorens/hui-plus/packages/_es/card' },
  Collect: { component: '@iflorens/hui-plus/packages/_es/collect' },
  CommentItem: { component: '@iflorens/hui-plus/packages/_es/comment' },
  CommentTextarea: { component: '@iflorens/hui-plus/packages/_es/comment' },
  CommentContent: { component: '@iflorens/hui-plus/packages/_es/comment' },
  ConfigProvider: { component: '@iflorens/hui-plus/packages/_es/configprovider' },
  DataExport: { component: '@iflorens/hui-plus/packages/_es/data-export' },
  Date: { component: '@iflorens/hui-plus/packages/_es/date' },
  Dropdown: { component: '@iflorens/hui-plus/packages/_es/dropdown' },
  Ellipsis: { component: '@iflorens/hui-plus/packages/_es/ellipsis' },
  Empty: { component: '@iflorens/hui-plus/packages/_es/empty' },
  Header: { component: '@iflorens/hui-plus/packages/_es/header' },
  Icon: { component: '@iflorens/hui-plus/packages/_es/icon' },
  IconButton: { component: '@iflorens/hui-plus/packages/_es/icon-button' },
  LeaseHeader: { component: '@iflorens/hui-plus/packages/_es/lease-header' },
  UpdownBtn: { component: '@iflorens/hui-plus/packages/_es/lease-header' },
  Modal: { component: '@iflorens/hui-plus/packages/_es/modal' },
  NumberRange: { component: '@iflorens/hui-plus/packages/_es/number-range' },
  TableTabs: { component: '@iflorens/hui-plus/packages/_es/pages' },
  Pages: { component: '@iflorens/hui-plus/packages/_es/pages' },
  Popover: { component: '@iflorens/hui-plus/packages/_es/popover' },
  Scroll: { component: '@iflorens/hui-plus/packages/_es/scroll' },
  Search: { component: '@iflorens/hui-plus/packages/_es/search' },
  Form: { component: '@iflorens/hui-plus/packages/_es/search' },
  SearchInput: { component: '@iflorens/hui-plus/packages/_es/search-input' },
  Select: { component: '@iflorens/hui-plus/packages/_es/select' },
  SelectTable: { component: '@iflorens/hui-plus/packages/_es/select-table' },
  Table: { component: '@iflorens/hui-plus/packages/_es/table' },
  Tabs: { component: '@iflorens/hui-plus/packages/_es/tabs' },
  TabBar: { component: '@iflorens/hui-plus/packages/_es/tabs' },
  TabPane: { component: '@iflorens/hui-plus/packages/_es/tabs' },
  TabNav: { component: '@iflorens/hui-plus/packages/_es/tabs' },
  Tag: { component: '@iflorens/hui-plus/packages/_es/tag' },
  TooltipEllipsis: { component: '@iflorens/hui-plus/packages/_es/tooltip-ellipsis' },
  Upload: { component: '@iflorens/hui-plus/packages/_es/upload' },
  Watermark: { component: '@iflorens/hui-plus/packages/_es/watermark' }
};
export default [
  'Anchor',
  'AnnexTable',
  'Annex',
  'AutoComplete',
  'AutoCompleteTable',
  'Button',
  'LongButton',
  'Card',
  'CardItem',
  'LeaseItem',
  'Collect',
  'CommentItem',
  'CommentTextarea',
  'CommentContent',
  'ConfigProvider',
  'DataExport',
  'Date',
  'Dropdown',
  'Ellipsis',
  'Empty',
  'Header',
  'Icon',
  'IconButton',
  'LeaseHeader',
  'UpdownBtn',
  'Modal',
  'NumberRange',
  'TableTabs',
  'Pages',
  'Popover',
  'Scroll',
  'Search',
  'Form',
  'SearchInput',
  'Select',
  'SelectTable',
  'Table',
  'Tabs',
  'TabBar',
  'TabPane',
  'TabNav',
  'Tag',
  'TooltipEllipsis',
  'Upload',
  'Watermark'
];
